version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-attendance-surekha
    ports:
      - "6578:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-attendance-surekha
    ports:
      - "3019:3019"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: attendance_db
      PORT: 3019
    restart: unless-stopped

  employee:
    build: ./Employee-Attendance
    container_name: employee-attendance-surekha
    ports:
      - "8090:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr:
    build: ./HR-Attendance
    container_name: hr-attendance-surekha
    ports:
      - "8091:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

